[tool.poetry]
name = "fast_flask_server"
version = "0.1.0"
description = ""
authors = ["ilia"]

[tool.poetry.dependencies]
python = "3.6.9"
flask = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
